### ISSUE TITLE
Копировать сертификаты при обновлении машины

### ISSUE THREAD

**Issue by pacahon** [cscenter/lms#554]
Сейчас с этим куча проблем, главная - `delegate_to` не понимает dynamic inventory и вообще не понятно, что туда надо поместить - ip или name. Если верить https://community.letsencrypt.org/t/moving-and-merging-certs-from-server-a-to-b/19015/3 то копировать надо папки, указанные в модуле ниже.

```
    - name: Try to copy certs from previous machine to local
      fetch:
        src: /etc/letsencrypt/{{ item }}
        dest: tmp/letsencrypt
        flat: yes
      loop:
        - archive
        - live
        - renewal
      # XXX: delegate_to doesn't recognize hosts from dynamic inventory
      delegate_to: "{{ groups[aws_ec2_prev_host_tag][0] }}"
      delegate_facts: True
      when: aws_ec2_prev_host_tag is defined
```

Протестировать такой вариант вручную. Если копирование прошло удачно - не запускать процесс обновления сертификатов.
